version: '3.8'

services:
  cloudviz:
    build: .
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    volumes:
      # Optional: Mount source code for development (uncomment next line for dev mode)
      # - .:/app
      # - /app/node_modules
    restart: unless-stopped

  # Development version (uncomment to use for development with hot reload)
  # cloudviz-dev:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - NODE_ENV=development
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   command: npm run dev
